-- Create table
CREATE TABLE bronze.category_code (
 
    category_id INT PRIMARY KEY,
 
    category_name VARCHAR(100) NOT NULL UNIQUE,
 
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
 
);
 
-- Insert category master data
INSERT INTO bronze.category_code (category_id, category_name)
VALUES
(11, 'RESIDENT INDIAN'),
(12, 'RESIDENT INDIVIDUAL'),
(13, 'HINDU UNDIVIDED FAMILY (HUF)'),
(14, 'SOLE PROPRIETOR'),
(15, 'PARTNERSHIP FIRM'),
(16, 'PRIVATE LIMITED COMPANY'),
(17, 'PUBLIC LIMITED COMPANY'),
(18, 'TRUST'),
(19, 'SOCIETY'),
(20, 'ASSOCIATION OF PERSONS (AOP)'),
(21, 'NRI REPATRIABLE'),
(22, 'NRI NON-REPATRIABLE'),
(23, 'FOREIGN NATIONAL'),
(24, 'FOREIGN INSTITUTIONAL INVESTOR (FII)'),
(25, 'QUALIFIED FOREIGN INVESTOR (QFI)'),
(26, 'BODY CORPORATE'),
(27, 'BANK'),
(28, 'FINANCIAL INSTITUTION'),
(29, 'MUTUAL FUND'),
(30, 'INSURANCE COMPANY'),
(31, 'PENSION FUND'),
(32, 'GOVERNMENT BODY'),
(33, 'DEFENCE ESTABLISHMENT'),
(34, 'CHARITABLE / RELIGIOUS TRUST'),
(35, 'LIMITED LIABILITY PARTNERSHIP (LLP)'),
(36, 'MINOR'),
(37, 'GUARDIAN'),
(38, 'NON-PROFIT ORGANIZATION'),
(39, 'OTHERS'),
(40, 'UNKNOWN');